name: firebase_encode
version: 1.0.0
author: Christopher Best <bestchris@gmail.com>
description: Encode strings to escape characters disallowed in Firebase keys
homepage: https://github.com/sirctseb/FirebaseEncode
environment:
  sdk: '>=2.0.0 <3.0.0'
documentation: http://sirctseb.github.io/FirebaseEncode
dependencies:
dev_dependencies:
  test: ^1.14.2
